version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    command: bash -lc "FLASK_DEBUG=1 flask run --host 0.0.0.0 --port 5000"
    environment:
      FLASK_APP: backend.app:create_app
      FLASK_DEBUG: "1"
      # Persist DB under /app/data (mapped to a named volume)
      SQLALCHEMY_DATABASE_URI: sqlite:////app/data/dev.db
      DATABASE_URL: sqlite:////app/data/dev.db
      PRINT_ROUTES: "1"
    volumes:
      - ./backend:/app/backend:delegated
      - backend_db:/app/data
    ports:
      - "5000:5000"

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    # Install once on container start, then run Vite
    command: sh -lc "npm ci --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      VITE_API_BASE_URL: http://localhost:5000
      # Avoid huge downloads in dev container
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    volumes:
      # Mount repo at /app so ../tsconfig.json resolves
      - ./frontend:/app/frontend:delegated
      - ./tsconfig.base.json:/app/tsconfig.base.json:ro
      # Keep node_modules inside the container
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_db:
