[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q --maxfail=1"

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.ruff.lint.per-file-ignores]
# Seed + tools scripts legitimately adjust sys.path before imports.
"backend/seeds/*.py" = ["E402"]
"backend/tools/*.py" = ["E402"]
