# ruff.toml
line-length = 100
target-version = "py312"     # or "py311" to match your runtime
src = ["backend"]
extend-exclude = ["frontend", "node_modules", ".venv", "venv", "dist", "build", "migrations"]

[lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E203", "E501"]    # formatter handles long lines

[lint.isort]
known-first-party = ["backend", "app", "models"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.per-file-ignores]
"backend/seeds/*.py" = ["E402"]
"backend/tools/*.py" = ["E402"]

[format]
quote-style = "single"
indent-style = "space"
