# ruff.toml
line-length = 100
target-version = "py39"

extend-exclude = [
  ".venv",
  "venv",
  "node_modules",
  "frontend",
  "dist",
  "build",
  "migrations",
]

[lint]
# E/F/W = pycodestyle/pyflakes; I = isort; B = bugbear; UP = pyupgrade; SIM = flake8-simplify
select = ["E", "F", "W", "I", "B", "UP", "SIM"]
ignore = ["E203", "E501"]
unfixable = ["UP038"]

[format]
quote-style = "single"           # <-- was "prefer-single" (invalid)
indent-style = "space"
skip-magic-trailing-comma = false
