name: Lint workflows

on:
  push:
    paths:
      - ".github/workflows/**"   # only run when workflow files change
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: shellcheck for inline bash checks in your workflow scripts
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Install actionlint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash \
          | bash -s -- latest "${HOME}/.local/bin"
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
          actionlint -version

      - name: Lint workflows
        run: actionlint -color
