name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend/requirements*.txt

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff pytest || true

      - name: Ruff (lint)
        run: ruff check .
        continue-on-error: true

      - name: Tests
        run: pytest -q
        continue-on-error: true

  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

  e2e:
    name: Playwright E2E
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    env:
      CI: true
      # Use SQLite in CI unless your app requires Postgres
      SQLALCHEMY_DATABASE_URI: sqlite:///ci.db
      # Update this if your Flask app module is different
      FLASK_APP: app
    steps:
      - uses: actions/checkout@v4

      # ---------- Frontend setup ----------
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright (Chromium only)
        working-directory: frontend
        run: npx playwright install --with-deps chromium

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # ---------- Backend setup ----------
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend/requirements*.txt

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Start backend (Flask) on :5001
        working-directory: backend
        run: |
          nohup python -m flask run --host 127.0.0.1 --port 5001 > ../flask.log 2>&1 &
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:5001/health >/dev/null 2>&1 || curl -fsS http://127.0.0.1:5001/ >/dev/null 2>&1; then
              echo "Backend is up"; break; fi
            sleep 2
          done

      - name: Start frontend preview on :5173
        working-directory: frontend
        run: |
          nohup npm run preview -- --host 127.0.0.1 --port 5173 > ../frontend-preview.log 2>&1 &
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:5173 >/dev/null 2>&1; then
              echo "Frontend is up"; break; fi
            sleep 2
          done

      - name: List discovered tests (debug)
        working-directory: frontend
        run: npx playwright test --list

      - name: Run Playwright tests (chromium)
        working-directory: frontend
        run: npx playwright test --project=chromium

      - name: Upload Playwright HTML report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: ignore

      - name: Upload server logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: |
            frontend/../frontend-preview.log
            backend/../flask.log
          if-no-files-found: ignore
