name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend/requirements*.txt
      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff pytest || true
      - name: Ruff (lint)
        run: ruff check .
        continue-on-error: true
      - name: Tests
        run: pytest -q
        continue-on-error: true

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install (npm ci)
        run: npm ci

      - name: Show npm scripts (debug)
        run: jq -r '.scripts' package.json || cat package.json

      - name: Build (fail if missing)
        run: |
          # Ensure "build" exists; fail loudly if not
          if ! jq -re '.scripts.build' package.json > /dev/null; then
            echo '❌ No "build" script found in package.json. Add one or remove --if-present.' >&2
            exit 1
          fi
          npm run build

      - name: List output (debug)
        run: |
          echo "Root:"
          ls -la
          echo "./frontend:"
          ls -la .
          echo "dist/ (if any):"
          ls -la dist || true
          echo "build/ (if any):"
          ls -la build || true

      - name: Determine build dir
        id: outdir
        run: |
          if [ -d dist ]; then
            echo "dir=dist" >> "$GITHUB_OUTPUT"
          elif [ -d build ]; then
            echo "dir=build" >> "$GITHUB_OUTPUT"
          else
            echo "❌ No dist/ or build/ directory found after build." >&2
            exit 1
          fi
          echo "Using $([[ -d dist ]] && echo dist || echo build) as build output"

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ${{ steps.outdir.outputs.dir }}/**
          if-no-files-found: error
          retention-days: 7


  e2e:
    name: E2E (Playwright)
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Install frontend dev deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Start preview server
        working-directory: frontend
        run: |
          npm run preview -- --port 5173 --strictPort &
          npx --yes wait-on http://127.0.0.1:5173

      # Uncomment if your tests call the API
      # - name: Start backend
      #   env:
      #     FLASK_APP: backend.app
      #     FLASK_ENV: production
      #   run: |
      #     python -m flask run --host=127.0.0.1 --port=5000 &
      #     npx --yes wait-on http://127.0.0.1:5000

      - name: Run Playwright tests
        working-directory: frontend
        run: npx playwright test ../tests/**/*.spec.ts --config ../playwright.config.ts

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
