name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - "tests/**"
      - "playwright.config.*"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - "frontend/**"
      - "tests/**"
      - "playwright.config.*"
      - ".github/workflows/ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend/requirements*.txt

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff pytest || true

      - name: Ruff (lint)
        run: ruff check .
        continue-on-error: true

      - name: Tests
        run: pytest -q
        continue-on-error: true

  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      # --- Backend setup ---
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend/requirements*.txt

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Start backend (Flask on 127.0.0.1:5000) and wait
        working-directory: backend
        env:
          FLASK_APP: app
          FLASK_DEBUG: "0"
          SQLALCHEMY_DATABASE_URI: sqlite:///ci.db
        run: |
          nohup flask run --host 127.0.0.1 --port 5000 --no-reload > ../flask.log 2>&1 &
          for i in {1..60}; do
            curl -fsS http://127.0.0.1:5000/api/acc_info && break
            sleep 1
          done
          curl -fsS http://127.0.0.1:5000/api/acc_info >/dev/null

      # --- Frontend setup (optional if your tests hit the site) ---
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Preview frontend on 127.0.0.1:5173 and wait
        working-directory: frontend
        run: |
          nohup npm run preview -- --host 127.0.0.1 --port 5173 > ../vite.log 2>&1 &
          for i in {1..60}; do
            curl -fsS http://127.0.0.1:5173/ && break
            sleep 1
          done
          curl -fsS http://127.0.0.1:5173/ >/dev/null

      # --- Playwright ---
      - name: Install Playwright (CLI only)
        run: npx -y playwright@1.48.2 install --with-deps chromium

      - name: Run Playwright tests
        env:
          CI: true
          API_URL: http://127.0.0.1:5000
        run: npx -y playwright@1.48.2 test --project=chromium

      # Debug logs if something fails
      - name: Dump server logs on failure
        if: failure()
        run: |
          echo "---- flask.log ----"
          tail -n +1 backend/flask.log || true
          echo "---- vite.log ----"
          tail -n +1 frontend/vite.log || true

