name: E2E (Playwright)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    # If your backend needs Postgres during tests, enable this service:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: financial_tracker_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      # point your Flask app to CI DB if your backend uses DATABASE_URL
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/financial_tracker_test
      # anything else your backend expects:
      FLASK_ENV: testing

    steps:
      - uses: actions/checkout@v4

      # Node for frontend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      # Python for backend
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # If you use Flask-Migrate, apply migrations here:
      - name: Prepare test DB (optional)
        working-directory: backend
        run: |
          if [ -f "migrations/README" ] || [ -d "migrations" ]; then
            flask db upgrade
          else
            echo "No migrations folder; skipping."
          fi

      # Install browsers (official action – handles Linux dependencies)
      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      # Run tests from repo root so playwright.config.ts is picked up
      - name: Run Playwright tests
        run: npx playwright test
